# ——————————异常处理——————————— #

<p id="t"></p>

## :book:异常处理 ##

:arrow_double_down:<a href="#a1">错误处理</a>

:arrow_double_down:<a href="#a2">捕获异常</a>

arrow_double_down:<a href="#a3">自定义异常类</a>

<p id="a1"><p>
  
### :crossed_flags:错误处理 ###

:arrow_double_up:<a href="#t">返回目录</a>

在Java程序运行期间出现一个错误，这个错误可能是由于文件包含了错误信息，或者网络连接出现问题造成的，也可能是其他错误。如果能够采用一些理智的行为。如过由于出现错误而使得某些错误没有完成，程序应该：
 
 * 返回到一种安全状态，并能够用户执行一些其他的命令
 
 * 允许用户保存所有操作的结果，并以妥善的方式终止程序

#### :circus_tent:Exception 类的层次  ####

所有的异常类是从 java.lang.Exception 类继承的子类。

Exception 类是 Throwable 类的子类。除了Exception类外，Throwable还有一个子类Error 。

Java 程序通常不捕获错误。错误一般发生在严重故障时，它们在Java程序处理的范畴之外。

Error 用来指示运行时环境发生的错误。

例如，JVM 内存溢出。一般地，程序不会从错误中恢复。

异常类有两个主要的子类：IOException 类和 RuntimeException 类。

![](http://www.runoob.com/wp-content/uploads/2013/12/12-130Q1234I6223.jpg)

Java语言规范将派生与Error类或RuntimeException类的所有异常称为非受查异常，所以其他的异常称为受查异常，这是两个很有用的术语，编译器将核查是否为所有的受查异常提供了异常处理器。

#### :circus_tent:Exception 声明受查异常  ####

在自己编写方法时，不必将所有可能抛出的异常都进行声明，至于什么时候需要在方法中用throws子句声明异常，什么异常必须使用throws子句声明，需要记住在遇到下面4种情况时应抛出异常：

 * 调用一个抛出受查异常的方法，例如FileInputStream构造器
 
 * 程序运行过程中发现错误，并利用throw语句抛出一个受查异常
 
 * 程序出现错误，例如数组索引溢出的异常
 
 * Java虚拟机和运行时库出现的内部错误。
 
 对于有些异常，如果没有处理器捕获这个异常，当前执行的线程就会结束。
 
 对于那些可能被他人使用的Java方法，应该根据异常规范在方法的首部声明这个方法可能抛出异常：
 
 ```java
     public  static void main(String arg[])throws IOException
    {
        
    }
```

如果一个方法有可能抛出多个受查异常类型，那么就必须在方法的首部列出所有的异常类，每个异常之间用逗号隔开：

```java
    public  static void main(String arg[])throws IOException, EOFException
    {

    }

```

但是不需要声明Java的内部错误，即从Error继承的错误，任何程序代码都具有抛出那些异常的潜能，而我们对其没有任何控制能力。同样，也不应该声明从RuntimeException继承的那些非受查异常，因为这些错误完全在我们控制下，因为这是你写的程序。

总之，一个方法必须声明所有可能抛出的受查异常，而非受查异常要么不可控制（Error），要么就应该避免发生。如果方法没有声明可能的受查异常，编译器就会发出一个错误消息。

#### :circus_tent:Exception 如何抛出异常  ####

首先要决定应该抛出什么类型的异常，将上述异常归结为IOException是一种很好的选择，仔细地阅读Java API文档之后会发现：EOFException异常描述的是：“在输入过程中，遇到了一个未预期的EOF后的信号”。这正是我们要抛出的异常，下面是抛出这个异常的语句：

throws new EOFException(); 或者：

EOFExcption e = new EOFExcption();
throw e;

<p id="a2"><p>
  
### :crossed_flags:捕获异常 ###

:arrow_double_up:<a href="#t">返回目录</a>

如果某个异常发生的时候没有在任何地方进行捕获，那程序就会终止，并在控制台打印异常信息。想要捕获异常必须设置try/catch语句块，如下所示：

```java
         try {
             //调试代码
         }
         catch (异常类型 变量){
             //错误处理
         }

```

如果在try语句中抛出了异常在catch中说明的异常类那么

* 程序跳过try语句中的类容

* 程序执行catch子句中的处理器代码。

如果在try中没有抛出异常，那么将会跳过catch子句内容。

简单演示：

```java
    public  static void main(String arg[])
    {
         try {
            int a = 8/0;
         }
         catch (ArithmeticException e){
           
             System.out.println(e.getMessage());
         }
    }
```

对于捕获异常，需要了解常见的异常类。如下表：

|异常|描述|
|:--:|:--|
|ArithmeticException	|当出现异常的运算条件时，抛出此异常。例如，一个整数"除以零"时，抛出此类的一个实例。|
|ArrayIndexOutOfBoundsException	|用非法索引访问数组时抛出的异常。如果索引为负或大于等于数组大小，则该索引为非法索引。|
|ArrayStoreException	|试图将错误类型的对象存储到一个对象数组时抛出的异常。|
|ClassCastException	|当试图将对象强制转换为不是实例的子类时，抛出该异常。|
|IllegalArgumentException|	抛出的异常表明向方法传递了一个不合法或不正确的参数。|
|IllegalMonitorStateException	|抛出的异常表明某一线程已经试图等待对象的监视器，或者试图通知其他正在等待对象的监视器而本身没有指定监视器的线程。|
|IllegalStateException	|在非法或不适当的时间调用方法时产生的信号。换句话说，即 Java 环境或 Java 应用程序没有处于请求操作所要求的适当状态下。|
|IllegalThreadStateException	|线程没有处于请求操作所要求的适当状态时抛出的异常。|
|IndexOutOfBoundsException|	指示某排序索引（例如对数组、字符串或向量的排序）超出范围时抛出。|
|NegativeArraySizeException	|如果应用程序试图创建大小为负的数组，则抛出该异常。|
|NullPointerException	|当应用程序试图在需要对象的地方使用 null 时，抛出该异常|
|NumberFormatException|	当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出该异常。|
|SecurityException	|由安全管理器抛出的异常，指示存在安全侵犯。|
|StringIndexOutOfBoundsException|	此异常由 String 方法抛出，指示索引或者为负，或者超出字符串的大小。|
|UnsupportedOperationException|	当不支持请求的操作时，抛出该异常。|

下面的表中列出了 Java 定义在 java.lang 包中的检查性异常类。

|异常|描述|
|:--:|:--|
|ClassNotFoundException	|应用程序试图加载类时，找不到相应的类，抛出该异常。|
|CloneNotSupportedException	|当调用 Object 类中的 clone 方法克隆对象，但该对象的类无法实现 Cloneable 接口时，抛出该异常。|
|IllegalAccessException	|拒绝访问一个类的时候，抛出该异常。|
|InstantiationException	|当试图使用 Class 类中的 newInstance 方法创建一个类的实例，而指定的类对象因为是一个接口或是一个抽象类而无法实例化时，抛出该异常。|
|InterruptedException	|一个线程被另一个线程中断，抛出该异常。|
|NoSuchFieldException	|请求的变量不存在|
|NoSuchMethodException|	请求的方法不存在|

所以在catch语句的括号里就需要填入以上信息，当然有些错误我们可能不是了解，由于所有的异常类是从 java.lang.Exception 类继承的子类。你可以填入Exception类型错误:

```java
    public  static void main(String arg[])
    {
         try {
            Scanner in = new Scanner(Paths.get("file.txt"));
         }
         catch (Exception e){
             System.out.println(e.getMessage());
         }
    }
```

控制台输出文件名，表示该文件没有存在。

关于异常类有以下方法：

|方法|方法及说明|
|:--:|:-------:|
|public String getMessage()|返回关于发生的异常的详细信息。这个消息在Throwable 类的构造函数中初始化了。|
|public Throwable getCause()|返回一个Throwable 对象代表异常原因。|
|public String toString()|使用getMessage()的结果返回类的串级名字。|
|	public void printStackTrace()|打印toString()结果和栈层次到System.err，即错误输出流。|
|public StackTraceElement [] getStackTrace()|返回一个包含堆栈层次的数组。下标为0的元素代表栈顶，最后一个元素代表方法调用堆栈的栈底。|
|public Throwable fillInStackTrace()|用当前的调用栈层次填充Throwable 对象栈层次，添加到栈层次任何先前信息中。|

#### :circus_tent:Exception捕获多个异常 ####

在一个try语句块中可以捕获多个异常类型，并对不同类型的异常做出不同异常处理，可以如下：

```java
    public  static void main(String arg[])
    {
         try {
            Scanner in = new Scanner(Paths.get("file.txt"));
         }
         catch (ArrayStoreException e1){
             System.out.println("错误信息是这个 ："+e1.getMessage());
         }
         catch (NullPointerException e2){
            System.out.println("错误信息是这个 ："+e2.getMessage());
         }
         catch (Exception e){
            System.out.println("错误信息是这个 ："+e.getMessage());
         }
    }
```

如上可以处理不同类型的错误信息。

#### :circus_tent:Exception再次抛出异常与异常链 ####

可以在catch子句中抛出异常，也就是throw语句：

```java
import java.io.*;
public class className
{
  public void deposit(double amount) throws RemoteException
  {
  // Method implementation
  throw new RemoteException();
  }
//Remainder of class definition
}

```
#### :circus_tent:Exceptionfinally关键字 ####

finally 关键字用来创建在 try 代码块后面执行的代码块。

无论是否发生异常，finally 代码块中的代码总会被执行。

在 finally 代码块中，可以运行清理类型等收尾善后性质的语句。

finally 代码块出现在 catch 代码块最后，语法如下：

```java
try{
// 程序代码
}
catch(异常类型1 异常的变量名1){
// 程序代码
}
catch(异常类型2 异常的变量名2){
// 程序代码
}
finally{
// 程序代码
}
```

<p id="a3"><p>
  
### :crossed_flags:自定义异常类 ###

:arrow_double_up:<a href="#t">返回目录</a>

在 Java 中你可以自定义异常。编写自己的异常类时需要记住下面的几点。

* 所有异常都必须是 Throwable 的子类。

* 如果希望写一个检查性异常类，则需要继承 Exception 类。

* 如果你想写一个运行时异常类，那么需要继承 RuntimeException 类。

可以像下面这样定义自己的异常类：

```java
class MyException extends Exception{
}
```

只继承Exception 类来创建的异常类是检查性异常类。

下面的 InsufficientFundsException 类是用户定义的异常类，它继承自 Exception。

一个异常类和其它任何类一样，包含有变量和方法。

以下实例是一个银行账户的模拟，通过银行卡的号码完成识别，可以进行存钱和取钱的操作:

```java

// 文件名InsufficientFundsException.java
import java.io.*;
//自定义异常类，继承Exception类
public class InsufficientFundsException extends Exception
{
    //此处的amount用来储存当出现异常（取出钱多于余额时）所缺乏的钱
    private double amount;
    public InsufficientFundsException(double amount)
    {
      this.amount = amount;
    }
    public double getAmount()
    {
      return amount;
    }
}
```

为了展示如何使用我们自定义的异常类，

在下面的 CheckingAccount 类中包含一个 withdraw() 方法抛出一个 InsufficientFundsException 异常。


```java
// 文件名称 CheckingAccount.java
import java.io.*;
//此类模拟银行账户
public class CheckingAccount
{
  //balance为余额，number为卡号
  private double balance;
  private int number;
  public CheckingAccount(int number)
  {
      this.number = number;
  }
  //方法：存钱
  public void deposit(double amount)
  {
      balance += amount;
  }
  //方法：取钱
  public void withdraw(double amount) throws
  InsufficientFundsException
  {
      if(amount <= balance)
      {
          balance -= amount;
      }
      else
      {
          double needs = amount - balance;
          throw new InsufficientFundsException(needs);
      }
  }
  //方法：返回余额
  public double getBalance()
  {
      return balance;
  }
  //方法：返回卡号
  public int getNumber()
  {
      return number;
  }
}

```

下面的 BankDemo 程序示范了如何调用 CheckingAccount 类的 deposit() 和 withdraw() 方法。

```java
//文件名称 BankDemo.java
public class BankDemo
{
    public static void main(String [] args)
    {
        CheckingAccount c = new CheckingAccount(101);
        System.out.println("Depositing $500...");
        c.deposit(500.00);
        try
        {
            System.out.println("\nWithdrawing $100...");
            c.withdraw(100.00);
            System.out.println("\nWithdrawing $600...");
            c.withdraw(600.00);
        }
        catch(InsufficientFundsException e)
        {
            System.out.println("Sorry, but you are short $"
            + e.getAmount());
            e.printStackTrace();
        }
    }   
}
```

